---
- hosts: development

  user: vagrant

  vars:
    - synced_folder: "{{ synced_folder }}"
    - host: "{{ host }}"

  gather_facts: yes

  roles:
    - common
    - webserver
    - database.mysql
    - elasticsearch

  become: True
